apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: <+stage.variables.service_name>
  annotations:
    run.googleapis.com/minScale: '2'
spec:
  template:
    spec:
      containers:
        - image: <+artifacts.primary.image>
          ports:
            - containerPort: 8080