apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: <+stage.variables.service_name>
  annotations:
    run.googleapis.com/minScale: '2'
    run.googleapis.com/invoker-iam-disabled: '<+stage.variables.invoker_iam_disabled>'
spec:
  template:
    spec:
      containers:
        - image: <+artifacts.primary.image>
          ports:
            - containerPort: 8080