apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gcrdemodev
  labels:
    owner: soto
  annotations:
    run.googleapis.com/minScale: '2'
spec:
  template:
    spec:
      containers:
        - image: <+artifacts.primary.image>
          ports:
            - containerPort: 8080