pipeline:
  name: Cloud Run Blue Green
  identifier: GCR_Pipeline_Sample
  tags: {}
  projectIdentifier: soto_sandbox
  orgIdentifier: sandbox
  stages:
    - stage:
        name: Cloud Run Blue Green Deploy
        identifier: google_cloud_run_service
        description: ""
        type: Deployment
        variables:
          - name: artifact_version
            type: String
            description: Artifact version to deploy
            required: true
            value: <+input>.default(neutral).selectOneFrom(neutral,blue,green)
          - name: primary_artifact
            type: String
            description: Primary artifact identifier
            required: true
            value: <+input>.default(artifact_gcr)
          - name: gcp_project
            type: String
            description: GCP project ID
            required: true
            value: <+input>.default(sales-209522)
          - name: gcp_region
            type: String
            description: GCP region for Cloud Run
            required: true
            value: <+input>.default(northamerica-northeast2)
          - name: service_name
            type: String
            description: Cloud Run service name
            required: true
            value: <+input>.default(gcrdemodev)
          - name: docker_connector
            type: String
            description: Docker registry connector for plugin images
            required: true
            value: <+input>.default(account.harnessImage)
          - name: k8s_connector
            type: String
            description: Kubernetes connector for step group infra
            required: true
            value: <+input>.default(org.se_sandbox_k8s)
          - name: gcp_connector
            type: String
            description: GCP connector for artifact registry and infrastructure
            required: true
            value: <+input>.default(account.GCP_Sales_Admin)
          - name: github_connector
            type: String
            description: GitHub connector for manifest repo
            required: true
            value: <+input>.default(alexsotoharness)
          - name: repo_name
            type: String
            description: GitHub repository name for manifest
            required: true
            value: <+input>.default(Cloud_Run_Sample)
          - name: repo_branch
            type: String
            description: Git branch for manifest
            required: true
            value: <+input>.default(dev)
          - name: gar_repository
            type: String
            description: Google Artifact Registry repository name
            required: true
            value: <+input>.default(soto-gar)
          - name: invoker_iam_disabled
            type: String
            description: Set to true if public access is enabled on the Cloud Run service, false for new services
            required: true
            value: <+input>.default(true)
          - name: service_ref
            type: String
            description: Harness service entity identifier
            required: true
            value: <+input>.default(service_gcr)
          - name: environment_ref
            type: String
            description: Harness environment entity identifier
            required: true
            value: <+input>.default(gcr_test)
          - name: infra_identifier
            type: String
            description: Harness infrastructure definition identifier
            required: true
            value: <+input>.default(gcr_test_infra)
        spec:
          deploymentType: GoogleCloudRun
          service:
            serviceRef: <+stage.variables.service_ref>
            serviceInputs:
              serviceDefinition:
                type: GoogleCloudRun
                spec:
                  manifests:
                    - manifest:
                        identifier: gcr_sample
                        type: GoogleCloudRunService
                        spec:
                          store:
                            type: Github
                            spec:
                              connectorRef: <+stage.variables.github_connector>
                              repoName: <+stage.variables.repo_name>
                              branch: <+stage.variables.repo_branch>
                  artifacts:
                    primary:
                      primaryArtifactRef: <+stage.variables.primary_artifact>
                      sources:
                        - identifier: artifact_gcr
                          type: GoogleArtifactRegistry
                          spec:
                            connectorRef: <+stage.variables.gcp_connector>
                            repositoryName: <+stage.variables.gar_repository>
                            project: <+stage.variables.gcp_project>
                            region: <+stage.variables.gcp_region>
                            package: <+stage.variables.service_name>
                            version: <+stage.variables.artifact_version>
          environment:
            environmentRef: <+stage.variables.environment_ref>
            deployToAll: false
            infrastructureDefinitions:
              - identifier: <+stage.variables.infra_identifier>
                inputs:
                  identifier: <+stage.variables.infra_identifier>
                  type: GoogleCloudRun
                  spec:
                    connectorRef: <+stage.variables.gcp_connector>
                    project: <+stage.variables.gcp_project>
                    region: <+stage.variables.gcp_region>
          execution:
            steps:
              - stepGroup:
                  steps:
                    - step:
                        type: DownloadManifests
                        name: Download Manifests
                        identifier: DownloadManifests
                        spec: {}
                        timeout: 10m
                    - step:
                        type: GoogleCloudRunPrepareRollbackData
                        name: Prepare Rollback Data
                        identifier: Google_Cloud_Run_Prepare_Rollback_Data
                        spec:
                          connectorRef: <+stage.variables.docker_connector>
                          image: harness/google-cloud-run-plugin:1.0.6-linux-amd64
                          imagePullPolicy: Always
                        timeout: 10m
                    - step:
                        type: GoogleCloudRunDeploy
                        name: Deploy To Staging
                        identifier: Deploy_To_Staging
                        spec:
                          connectorRef: <+stage.variables.docker_connector>
                          image: harness/google-cloud-run-plugin:1.0.6-linux-amd64
                          imagePullPolicy: Always
                          skipTrafficShift: true
                        timeout: 10m
                    - step:
                        type: GoogleCloudRunTrafficShift
                        name: Tag New Revision
                        identifier: Tag_New_Revision
                        spec:
                          connectorRef: <+stage.variables.docker_connector>
                          revisionTrafficDetails:
                            - revisionName: LATEST
                              trafficValue: 0
                              tag: staging
                            - revisionName: <+execution.steps.Google_Cloud_Run_Step_Group.steps.Google_Cloud_Run_Prepare_Rollback_Data.GoogleCloudRunPrepareRollbackDataOutcome.revisionMetadata[0].revisionName>
                              trafficValue: 100
                              tag: primary
                          image: harness/google-cloud-run-plugin:1.0.6-linux-amd64
                        timeout: 10m
                        when:
                          stageStatus: Success
                          condition: <+execution.steps.Google_Cloud_Run_Step_Group.steps.Google_Cloud_Run_Prepare_Rollback_Data.GoogleCloudRunPrepareRollbackDataOutcome.revisionMetadata[0].revisionName> != null
                  name: Cloud Run Deploy to Staging
                  identifier: Google_Cloud_Run_Step_Group
                  sharedPaths:
                    - /var/run
                    - /var/lib/docker
                  stepGroupInfra:
                    type: KubernetesDirect
                    spec:
                      connectorRef: <+stage.variables.k8s_connector>
                      namespace: default
              - step:
                  type: HarnessApproval
                  name: Cutover Approval
                  identifier: Cutover_Approval
                  spec:
                    approvalMessage: Test the new revision before approving cutover to primary.
                    includePipelineExecutionHistory: true
                    isAutoRejectEnabled: false
                    approvers:
                      userGroups:
                        - account._account_all_users
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
              - stepGroup:
                  name: Cloud Run Traffic Shift
                  identifier: Cloud_Run_Traffic_Shift
                  steps:
                    - step:
                        type: DownloadManifests
                        name: Download Manifests
                        identifier: DownloadManifests_Cutover
                        spec: {}
                        timeout: 10m
                    - step:
                        type: GoogleCloudRunTrafficShift
                        name: Shift Traffic To Primary
                        identifier: Shift_Traffic_To_Primary
                        spec:
                          connectorRef: <+stage.variables.docker_connector>
                          revisionTrafficDetails:
                            - revisionName: LATEST
                              trafficValue: 100
                              tag: primary
                          image: harness/google-cloud-run-plugin:1.0.6-linux-amd64
                        timeout: 10m
                  sharedPaths:
                    - /var/run
                    - /var/lib/docker
                  stepGroupInfra:
                    type: KubernetesDirect
                    spec:
                      connectorRef: <+stage.variables.k8s_connector>
                      namespace: default
            rollbackSteps:
              - stepGroup:
                  identifier: Google_Cloud_Run_Rollback_Step_Group
                  name: Google Cloud Run Rollback Step Group
                  steps:
                    - step:
                        type: GoogleCloudRunRollback
                        name: Google Cloud Run Rollback
                        identifier: Google_Cloud_Run_Rollback
                        spec:
                          connectorRef: <+stage.variables.docker_connector>
                          image: harness/google-cloud-run-plugin:1.0.6-linux-amd64
                          imagePullPolicy: Always
                        timeout: 10m
                  sharedPaths:
                    - /var/run
                    - /var/lib/docker
                  stepGroupInfra:
                    type: KubernetesDirect
                    spec:
                      connectorRef: <+stage.variables.k8s_connector>
                      namespace: default
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
