service:
  name: service_gcr
  identifier: service_gcr
  serviceDefinition:
    type: GoogleCloudRun
    spec:
      manifests:
        - manifest:
            identifier: gcr_sample
            type: GoogleCloudRunService
            spec:
              store:
                type: Github
                spec:
                  connectorRef: alexsotoharness
                  repoName: Cloud_Run_Sample
                  gitFetchType: Branch
                  branch: main
                  paths:
                    - harness-cd-pipeline/manifest.yaml
      artifacts:
        primary:
          primaryArtifactRef: <+input>
          sources:
            - spec:
                connectorRef: account.GCP_Sales_Admin
                repositoryType: docker
                project: sales-209522
                region: northamerica-northeast2
                repositoryName: soto-gar
                package: gcrdemodev
                version: <+input>
              identifier: artifact_gcr
              type: GoogleArtifactRegistry
  gitOpsEnabled: false
  orgIdentifier: sandbox
  projectIdentifier: soto_sandbox